### ISSUE TITLE
Add an API gateway to the project

### ISSUE THREAD

**Issue by MarcDuQuesne** [MarcDuQuesne/CDKSAM#1]

**Comment by pelssers** [comment]
I've been trying this on branch feature/api-gateway. For the CDK it should be as simple as adding a `apigateway.StepFunctionsRestApi` to start execution of the state machine. When testing locally with SAM (instructions in README) I get `ValueError: Function name is required` when it's invoking the Lambda, reading online that this might be a difference between how cdk and sam handle aliases.

**Comment by MarcDuQuesne** [comment]
have you tried adding a function name, if not present?

**Comment by MarcDuQuesne** [comment]
I did and of course it's not enough. I added some integrations with lambdas directly, and those do work, but the integration with the stepfunction does not because of the alias stuff (see my commits in your branch).

I guess you arleady saw: https://stackoverflow.com/questions/63536861/aws-sam-starting-local-api-returns-function-name-is-required-error/63713747#63713747

Let's see what we can do, but if it does not work out of the box - I am afraid there's not much we can do.

**Comment by MarcDuQuesne** [comment]
@pelssers I am getting something very strange - I stripped down the whole stack to just the api gateway to:

```
    const api = new apigw.RestApi(this, "ETL_API");

    api.root.addMethod(
      "ANY",
      new apigw.MockIntegration({
        integrationResponses: [{ statusCode: "200" }],
      }),
      {
        methodResponses: [{ statusCode: "200" }],
      }
    );
```

and still I get the problem with ValueError: Function name is required.

could you give it a try?
